# Project information
site_name: Mobile.BuildTools
site_description: Project docs for the Mobile.BuildTools
site_author: Dan Siegel
site_url: https://mobilebuildtools.com/

# Repository
repo_name: dansiegel/Mobile.BuildTools
repo_url: https://github.com/dansiegel/Mobile.BuildTools
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2017 - 2026 Dan Siegel'

# Configuration
theme:
  name: 'material'
  custom_dir: 'theme'
  icon:
    repo: fontawesome/brands/github
  logo: assets/icon.svg
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    primary: white
    accent: deep-orange
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/icon.svg

extra:
  social:
    - icon: fontawesome/brands/blogger
      link: https://dansiegel.net
    - icon: fontawesome/brands/github
      link: https://github.com/dansiegel
    - icon: fontawesome/brands/twitch
      link: https://twitch.tv/dansiegel
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DanJSiegel
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/dansiegel
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/DanSiegel

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

nav:
  - Mobile.BuildTools:
    - Getting Started: index.md
    - .NET MAUI and Uno Platform: maui.md
    - App Configuration:
      - Intro: config/index.md
      - App Settings:
        - Intro: config/appsettings/index.md
        - Configuration: config/appsettings/configuration.md
        - F.A.Q.: config/appsettings/faq.md
      - App.config:
        - Intro: config/app.config/index.md
        - Transformations: config/app.config/transformations.md
        - In Code: config/app.config/in-code.md
    - App Manifests:
      - Tokenized Manifests: manifests/index.md
      - Build Versioning: manifests/versioning.md
    - Configuration: configuration.md
    - Google Firebase: google/index.md
    - Image Assets:
      - Getting Started: images/index.md
      - Configuring Images: images/configuring-images.md
      - Build Customization: images/build-customization.md
      - Built In Templates: images/built-in-templates.md
    - Release Note Generation: release-notes.md
    - Continuous Integration:
      - Platforms: continuous-integration/platforms.md
      - Setup: continuous-integration/setup.md
    - F.A.Q.: faq.md
    - Appendix:
      - Upgrading from 1.X: appendix/upgrade.md
      - Apple Push Notifications: appendix/aps.md
      - JSON Schemas: appendix/json-schemas.md
      - MSBuild Properties: appendix/msbuild-props.md
    - Credits: credits.md
