cls
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-top-flatpurple.png --export-id=dev-top-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tl-flatpurple.png --export-id=dev-tl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tr-flatpurple.png --export-id=dev-tr-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bl-flatpurple.png --export-id=dev-bl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-br-flatpurple.png --export-id=dev-br-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bot-flatpurple.png --export-id=dev-bot-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-top-flatpurple.png --export-id=debug-top-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tl-flatpurple.png --export-id=debug-tl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tr-flatpurple.png --export-id=debug-tr-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bl-flatpurple.png --export-id=debug-bl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-br-flatpurple.png --export-id=debug-br-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bot-flatpurple.png --export-id=debug-bot-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-top-flatpurple.png --export-id=qa-top-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tl-flatpurple.png --export-id=qa-tl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tr-flatpurple.png --export-id=qa-tr-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bl-flatpurple.png --export-id=qa-bl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-br-flatpurple.png --export-id=qa-br-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bot-flatpurple.png --export-id=qa-bot-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-top-flatpurple.png --export-id=uat-top-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tl-flatpurple.png --export-id=uat-tl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tr-flatpurple.png --export-id=uat-tr-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bl-flatpurple.png --export-id=uat-bl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-br-flatpurple.png --export-id=uat-br-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bot-flatpurple.png --export-id=uat-bot-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-top-flatpurple.png --export-id=stage-top-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tl-flatpurple.png --export-id=stage-tl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tr-flatpurple.png --export-id=stage-tr-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bl-flatpurple.png --export-id=stage-bl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-br-flatpurple.png --export-id=stage-br-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bot-flatpurple.png --export-id=stage-bot-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-top-flatpurple.png --export-id=preview-top-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tl-flatpurple.png --export-id=preview-tl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tr-flatpurple.png --export-id=preview-tr-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bl-flatpurple.png --export-id=preview-bl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-br-flatpurple.png --export-id=preview-br-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bot-flatpurple.png --export-id=preview-bot-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-top-flatpurple.png --export-id=alpha-top-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tl-flatpurple.png --export-id=alpha-tl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tr-flatpurple.png --export-id=alpha-tr-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bl-flatpurple.png --export-id=alpha-bl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-br-flatpurple.png --export-id=alpha-br-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bot-flatpurple.png --export-id=alpha-bot-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-top-flatpurple.png --export-id=beta-top-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tl-flatpurple.png --export-id=beta-tl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tr-flatpurple.png --export-id=beta-tr-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bl-flatpurple.png --export-id=beta-bl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-br-flatpurple.png --export-id=beta-br-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bot-flatpurple.png --export-id=beta-bot-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-top-flatpurple.png --export-id=free-top-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tl-flatpurple.png --export-id=free-tl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tr-flatpurple.png --export-id=free-tr-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bl-flatpurple.png --export-id=free-bl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-br-flatpurple.png --export-id=free-br-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bot-flatpurple.png --export-id=free-bot-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-top-flatpurple.png --export-id=pro-top-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tl-flatpurple.png --export-id=pro-tl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tr-flatpurple.png --export-id=pro-tr-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bl-flatpurple.png --export-id=pro-bl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-br-flatpurple.png --export-id=pro-br-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bot-flatpurple.png --export-id=pro-bot-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-top-flatpurple.png --export-id=lite-top-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tl-flatpurple.png --export-id=lite-tl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tr-flatpurple.png --export-id=lite-tr-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bl-flatpurple.png --export-id=lite-bl-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-br-flatpurple.png --export-id=lite-br-flatpurple flatpurple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bot-flatpurple.png --export-id=lite-bot-flatpurple flatpurple.svg
