cls
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-top-green.png --export-id=dev-top-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tl-green.png --export-id=dev-tl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tr-green.png --export-id=dev-tr-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bl-green.png --export-id=dev-bl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-br-green.png --export-id=dev-br-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bot-green.png --export-id=dev-bot-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-top-green.png --export-id=debug-top-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tl-green.png --export-id=debug-tl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tr-green.png --export-id=debug-tr-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bl-green.png --export-id=debug-bl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-br-green.png --export-id=debug-br-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bot-green.png --export-id=debug-bot-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-top-green.png --export-id=qa-top-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tl-green.png --export-id=qa-tl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tr-green.png --export-id=qa-tr-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bl-green.png --export-id=qa-bl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-br-green.png --export-id=qa-br-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bot-green.png --export-id=qa-bot-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-top-green.png --export-id=uat-top-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tl-green.png --export-id=uat-tl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tr-green.png --export-id=uat-tr-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bl-green.png --export-id=uat-bl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-br-green.png --export-id=uat-br-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bot-green.png --export-id=uat-bot-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-top-green.png --export-id=stage-top-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tl-green.png --export-id=stage-tl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tr-green.png --export-id=stage-tr-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bl-green.png --export-id=stage-bl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-br-green.png --export-id=stage-br-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bot-green.png --export-id=stage-bot-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-top-green.png --export-id=preview-top-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tl-green.png --export-id=preview-tl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tr-green.png --export-id=preview-tr-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bl-green.png --export-id=preview-bl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-br-green.png --export-id=preview-br-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bot-green.png --export-id=preview-bot-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-top-green.png --export-id=alpha-top-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tl-green.png --export-id=alpha-tl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tr-green.png --export-id=alpha-tr-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bl-green.png --export-id=alpha-bl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-br-green.png --export-id=alpha-br-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bot-green.png --export-id=alpha-bot-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-top-green.png --export-id=beta-top-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tl-green.png --export-id=beta-tl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tr-green.png --export-id=beta-tr-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bl-green.png --export-id=beta-bl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-br-green.png --export-id=beta-br-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bot-green.png --export-id=beta-bot-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-top-green.png --export-id=free-top-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tl-green.png --export-id=free-tl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tr-green.png --export-id=free-tr-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bl-green.png --export-id=free-bl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-br-green.png --export-id=free-br-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bot-green.png --export-id=free-bot-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-top-green.png --export-id=pro-top-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tl-green.png --export-id=pro-tl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tr-green.png --export-id=pro-tr-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bl-green.png --export-id=pro-bl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-br-green.png --export-id=pro-br-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bot-green.png --export-id=pro-bot-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-top-green.png --export-id=lite-top-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tl-green.png --export-id=lite-tl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tr-green.png --export-id=lite-tr-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bl-green.png --export-id=lite-bl-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-br-green.png --export-id=lite-br-green green.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bot-green.png --export-id=lite-bot-green green.svg
