cls
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-top-blue.png --export-id=dev-top-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tl-blue.png --export-id=dev-tl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tr-blue.png --export-id=dev-tr-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bl-blue.png --export-id=dev-bl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-br-blue.png --export-id=dev-br-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bot-blue.png --export-id=dev-bot-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-top-blue.png --export-id=debug-top-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tl-blue.png --export-id=debug-tl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tr-blue.png --export-id=debug-tr-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bl-blue.png --export-id=debug-bl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-br-blue.png --export-id=debug-br-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bot-blue.png --export-id=debug-bot-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-top-blue.png --export-id=qa-top-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tl-blue.png --export-id=qa-tl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tr-blue.png --export-id=qa-tr-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bl-blue.png --export-id=qa-bl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-br-blue.png --export-id=qa-br-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bot-blue.png --export-id=qa-bot-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-top-blue.png --export-id=uat-top-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tl-blue.png --export-id=uat-tl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tr-blue.png --export-id=uat-tr-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bl-blue.png --export-id=uat-bl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-br-blue.png --export-id=uat-br-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bot-blue.png --export-id=uat-bot-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-top-blue.png --export-id=stage-top-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tl-blue.png --export-id=stage-tl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tr-blue.png --export-id=stage-tr-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bl-blue.png --export-id=stage-bl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-br-blue.png --export-id=stage-br-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bot-blue.png --export-id=stage-bot-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-top-blue.png --export-id=preview-top-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tl-blue.png --export-id=preview-tl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tr-blue.png --export-id=preview-tr-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bl-blue.png --export-id=preview-bl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-br-blue.png --export-id=preview-br-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bot-blue.png --export-id=preview-bot-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-top-blue.png --export-id=alpha-top-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tl-blue.png --export-id=alpha-tl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tr-blue.png --export-id=alpha-tr-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bl-blue.png --export-id=alpha-bl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-br-blue.png --export-id=alpha-br-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bot-blue.png --export-id=alpha-bot-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-top-blue.png --export-id=beta-top-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tl-blue.png --export-id=beta-tl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tr-blue.png --export-id=beta-tr-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bl-blue.png --export-id=beta-bl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-br-blue.png --export-id=beta-br-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bot-blue.png --export-id=beta-bot-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-top-blue.png --export-id=free-top-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tl-blue.png --export-id=free-tl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tr-blue.png --export-id=free-tr-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bl-blue.png --export-id=free-bl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-br-blue.png --export-id=free-br-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bot-blue.png --export-id=free-bot-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-top-blue.png --export-id=pro-top-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tl-blue.png --export-id=pro-tl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tr-blue.png --export-id=pro-tr-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bl-blue.png --export-id=pro-bl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-br-blue.png --export-id=pro-br-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bot-blue.png --export-id=pro-bot-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-top-blue.png --export-id=lite-top-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tl-blue.png --export-id=lite-tl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tr-blue.png --export-id=lite-tr-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bl-blue.png --export-id=lite-bl-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-br-blue.png --export-id=lite-br-blue blue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bot-blue.png --export-id=lite-bot-blue blue.svg

