cls
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-top-yellow.png --export-id=dev-top-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tl-yellow.png --export-id=dev-tl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tr-yellow.png --export-id=dev-tr-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bl-yellow.png --export-id=dev-bl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-br-yellow.png --export-id=dev-br-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bot-yellow.png --export-id=dev-bot-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-top-yellow.png --export-id=debug-top-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tl-yellow.png --export-id=debug-tl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tr-yellow.png --export-id=debug-tr-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bl-yellow.png --export-id=debug-bl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-br-yellow.png --export-id=debug-br-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bot-yellow.png --export-id=debug-bot-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-top-yellow.png --export-id=qa-top-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tl-yellow.png --export-id=qa-tl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tr-yellow.png --export-id=qa-tr-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bl-yellow.png --export-id=qa-bl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-br-yellow.png --export-id=qa-br-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bot-yellow.png --export-id=qa-bot-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-top-yellow.png --export-id=uat-top-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tl-yellow.png --export-id=uat-tl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tr-yellow.png --export-id=uat-tr-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bl-yellow.png --export-id=uat-bl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-br-yellow.png --export-id=uat-br-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bot-yellow.png --export-id=uat-bot-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-top-yellow.png --export-id=stage-top-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tl-yellow.png --export-id=stage-tl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tr-yellow.png --export-id=stage-tr-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bl-yellow.png --export-id=stage-bl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-br-yellow.png --export-id=stage-br-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bot-yellow.png --export-id=stage-bot-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-top-yellow.png --export-id=preview-top-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tl-yellow.png --export-id=preview-tl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tr-yellow.png --export-id=preview-tr-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bl-yellow.png --export-id=preview-bl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-br-yellow.png --export-id=preview-br-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bot-yellow.png --export-id=preview-bot-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-top-yellow.png --export-id=alpha-top-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tl-yellow.png --export-id=alpha-tl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tr-yellow.png --export-id=alpha-tr-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bl-yellow.png --export-id=alpha-bl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-br-yellow.png --export-id=alpha-br-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bot-yellow.png --export-id=alpha-bot-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-top-yellow.png --export-id=beta-top-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tl-yellow.png --export-id=beta-tl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tr-yellow.png --export-id=beta-tr-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bl-yellow.png --export-id=beta-bl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-br-yellow.png --export-id=beta-br-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bot-yellow.png --export-id=beta-bot-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-top-yellow.png --export-id=free-top-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tl-yellow.png --export-id=free-tl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tr-yellow.png --export-id=free-tr-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bl-yellow.png --export-id=free-bl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-br-yellow.png --export-id=free-br-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bot-yellow.png --export-id=free-bot-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-top-yellow.png --export-id=pro-top-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tl-yellow.png --export-id=pro-tl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tr-yellow.png --export-id=pro-tr-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bl-yellow.png --export-id=pro-bl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-br-yellow.png --export-id=pro-br-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bot-yellow.png --export-id=pro-bot-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-top-yellow.png --export-id=lite-top-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tl-yellow.png --export-id=lite-tl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tr-yellow.png --export-id=lite-tr-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bl-yellow.png --export-id=lite-bl-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-br-yellow.png --export-id=lite-br-yellow yellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bot-yellow.png --export-id=lite-bot-yellow yellow.svg
