cls
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-top-white.png --export-id=dev-top-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tl-white.png --export-id=dev-tl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tr-white.png --export-id=dev-tr-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bl-white.png --export-id=dev-bl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-br-white.png --export-id=dev-br-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bot-white.png --export-id=dev-bot-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-top-white.png --export-id=debug-top-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tl-white.png --export-id=debug-tl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tr-white.png --export-id=debug-tr-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bl-white.png --export-id=debug-bl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-br-white.png --export-id=debug-br-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bot-white.png --export-id=debug-bot-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-top-white.png --export-id=qa-top-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tl-white.png --export-id=qa-tl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tr-white.png --export-id=qa-tr-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bl-white.png --export-id=qa-bl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-br-white.png --export-id=qa-br-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bot-white.png --export-id=qa-bot-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-top-white.png --export-id=uat-top-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tl-white.png --export-id=uat-tl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tr-white.png --export-id=uat-tr-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bl-white.png --export-id=uat-bl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-br-white.png --export-id=uat-br-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bot-white.png --export-id=uat-bot-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-top-white.png --export-id=stage-top-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tl-white.png --export-id=stage-tl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tr-white.png --export-id=stage-tr-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bl-white.png --export-id=stage-bl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-br-white.png --export-id=stage-br-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bot-white.png --export-id=stage-bot-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-top-white.png --export-id=preview-top-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tl-white.png --export-id=preview-tl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tr-white.png --export-id=preview-tr-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bl-white.png --export-id=preview-bl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-br-white.png --export-id=preview-br-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bot-white.png --export-id=preview-bot-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-top-white.png --export-id=alpha-top-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tl-white.png --export-id=alpha-tl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tr-white.png --export-id=alpha-tr-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bl-white.png --export-id=alpha-bl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-br-white.png --export-id=alpha-br-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bot-white.png --export-id=alpha-bot-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-top-white.png --export-id=beta-top-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tl-white.png --export-id=beta-tl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tr-white.png --export-id=beta-tr-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bl-white.png --export-id=beta-bl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-br-white.png --export-id=beta-br-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bot-white.png --export-id=beta-bot-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-top-white.png --export-id=free-top-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tl-white.png --export-id=free-tl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tr-white.png --export-id=free-tr-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bl-white.png --export-id=free-bl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-br-white.png --export-id=free-br-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bot-white.png --export-id=free-bot-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-top-white.png --export-id=pro-top-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tl-white.png --export-id=pro-tl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tr-white.png --export-id=pro-tr-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bl-white.png --export-id=pro-bl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-br-white.png --export-id=pro-br-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bot-white.png --export-id=pro-bot-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-top-white.png --export-id=lite-top-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tl-white.png --export-id=lite-tl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tr-white.png --export-id=lite-tr-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bl-white.png --export-id=lite-bl-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-br-white.png --export-id=lite-br-white white.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bot-white.png --export-id=lite-bot-white white.svg

