cls
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-top-flatgreen.png --export-id=dev-top-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tl-flatgreen.png --export-id=dev-tl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tr-flatgreen.png --export-id=dev-tr-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bl-flatgreen.png --export-id=dev-bl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-br-flatgreen.png --export-id=dev-br-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bot-flatgreen.png --export-id=dev-bot-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-top-flatgreen.png --export-id=debug-top-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tl-flatgreen.png --export-id=debug-tl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tr-flatgreen.png --export-id=debug-tr-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bl-flatgreen.png --export-id=debug-bl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-br-flatgreen.png --export-id=debug-br-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bot-flatgreen.png --export-id=debug-bot-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-top-flatgreen.png --export-id=qa-top-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tl-flatgreen.png --export-id=qa-tl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tr-flatgreen.png --export-id=qa-tr-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bl-flatgreen.png --export-id=qa-bl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-br-flatgreen.png --export-id=qa-br-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bot-flatgreen.png --export-id=qa-bot-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-top-flatgreen.png --export-id=uat-top-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tl-flatgreen.png --export-id=uat-tl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tr-flatgreen.png --export-id=uat-tr-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bl-flatgreen.png --export-id=uat-bl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-br-flatgreen.png --export-id=uat-br-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bot-flatgreen.png --export-id=uat-bot-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-top-flatgreen.png --export-id=stage-top-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tl-flatgreen.png --export-id=stage-tl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tr-flatgreen.png --export-id=stage-tr-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bl-flatgreen.png --export-id=stage-bl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-br-flatgreen.png --export-id=stage-br-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bot-flatgreen.png --export-id=stage-bot-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-top-flatgreen.png --export-id=preview-top-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tl-flatgreen.png --export-id=preview-tl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tr-flatgreen.png --export-id=preview-tr-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bl-flatgreen.png --export-id=preview-bl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-br-flatgreen.png --export-id=preview-br-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bot-flatgreen.png --export-id=preview-bot-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-top-flatgreen.png --export-id=alpha-top-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tl-flatgreen.png --export-id=alpha-tl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tr-flatgreen.png --export-id=alpha-tr-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bl-flatgreen.png --export-id=alpha-bl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-br-flatgreen.png --export-id=alpha-br-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bot-flatgreen.png --export-id=alpha-bot-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-top-flatgreen.png --export-id=beta-top-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tl-flatgreen.png --export-id=beta-tl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tr-flatgreen.png --export-id=beta-tr-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bl-flatgreen.png --export-id=beta-bl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-br-flatgreen.png --export-id=beta-br-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bot-flatgreen.png --export-id=beta-bot-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-top-flatgreen.png --export-id=free-top-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tl-flatgreen.png --export-id=free-tl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tr-flatgreen.png --export-id=free-tr-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bl-flatgreen.png --export-id=free-bl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-br-flatgreen.png --export-id=free-br-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bot-flatgreen.png --export-id=free-bot-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-top-flatgreen.png --export-id=pro-top-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tl-flatgreen.png --export-id=pro-tl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tr-flatgreen.png --export-id=pro-tr-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bl-flatgreen.png --export-id=pro-bl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-br-flatgreen.png --export-id=pro-br-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bot-flatgreen.png --export-id=pro-bot-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-top-flatgreen.png --export-id=lite-top-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tl-flatgreen.png --export-id=lite-tl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tr-flatgreen.png --export-id=lite-tr-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bl-flatgreen.png --export-id=lite-bl-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-br-flatgreen.png --export-id=lite-br-flatgreen flatgreen.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bot-flatgreen.png --export-id=lite-bot-flatgreen flatgreen.svg
