cls
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-top-flatyellow.png --export-id=dev-top-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tl-flatyellow.png --export-id=dev-tl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tr-flatyellow.png --export-id=dev-tr-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bl-flatyellow.png --export-id=dev-bl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-br-flatyellow.png --export-id=dev-br-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bot-flatyellow.png --export-id=dev-bot-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-top-flatyellow.png --export-id=debug-top-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tl-flatyellow.png --export-id=debug-tl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tr-flatyellow.png --export-id=debug-tr-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bl-flatyellow.png --export-id=debug-bl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-br-flatyellow.png --export-id=debug-br-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bot-flatyellow.png --export-id=debug-bot-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-top-flatyellow.png --export-id=qa-top-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tl-flatyellow.png --export-id=qa-tl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tr-flatyellow.png --export-id=qa-tr-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bl-flatyellow.png --export-id=qa-bl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-br-flatyellow.png --export-id=qa-br-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bot-flatyellow.png --export-id=qa-bot-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-top-flatyellow.png --export-id=uat-top-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tl-flatyellow.png --export-id=uat-tl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tr-flatyellow.png --export-id=uat-tr-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bl-flatyellow.png --export-id=uat-bl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-br-flatyellow.png --export-id=uat-br-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bot-flatyellow.png --export-id=uat-bot-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-top-flatyellow.png --export-id=stage-top-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tl-flatyellow.png --export-id=stage-tl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tr-flatyellow.png --export-id=stage-tr-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bl-flatyellow.png --export-id=stage-bl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-br-flatyellow.png --export-id=stage-br-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bot-flatyellow.png --export-id=stage-bot-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-top-flatyellow.png --export-id=preview-top-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tl-flatyellow.png --export-id=preview-tl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tr-flatyellow.png --export-id=preview-tr-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bl-flatyellow.png --export-id=preview-bl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-br-flatyellow.png --export-id=preview-br-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bot-flatyellow.png --export-id=preview-bot-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-top-flatyellow.png --export-id=alpha-top-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tl-flatyellow.png --export-id=alpha-tl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tr-flatyellow.png --export-id=alpha-tr-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bl-flatyellow.png --export-id=alpha-bl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-br-flatyellow.png --export-id=alpha-br-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bot-flatyellow.png --export-id=alpha-bot-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-top-flatyellow.png --export-id=beta-top-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tl-flatyellow.png --export-id=beta-tl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tr-flatyellow.png --export-id=beta-tr-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bl-flatyellow.png --export-id=beta-bl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-br-flatyellow.png --export-id=beta-br-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bot-flatyellow.png --export-id=beta-bot-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-top-flatyellow.png --export-id=free-top-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tl-flatyellow.png --export-id=free-tl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tr-flatyellow.png --export-id=free-tr-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bl-flatyellow.png --export-id=free-bl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-br-flatyellow.png --export-id=free-br-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bot-flatyellow.png --export-id=free-bot-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-top-flatyellow.png --export-id=pro-top-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tl-flatyellow.png --export-id=pro-tl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tr-flatyellow.png --export-id=pro-tr-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bl-flatyellow.png --export-id=pro-bl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-br-flatyellow.png --export-id=pro-br-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bot-flatyellow.png --export-id=pro-bot-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-top-flatyellow.png --export-id=lite-top-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tl-flatyellow.png --export-id=lite-tl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tr-flatyellow.png --export-id=lite-tr-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bl-flatyellow.png --export-id=lite-bl-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-br-flatyellow.png --export-id=lite-br-flatyellow flatyellow.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bot-flatyellow.png --export-id=lite-bot-flatyellow flatyellow.svg
