cls
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-top-flatred.png --export-id=dev-top-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tl-flatred.png --export-id=dev-tl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tr-flatred.png --export-id=dev-tr-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bl-flatred.png --export-id=dev-bl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-br-flatred.png --export-id=dev-br-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bot-flatred.png --export-id=dev-bot-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-top-flatred.png --export-id=debug-top-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tl-flatred.png --export-id=debug-tl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tr-flatred.png --export-id=debug-tr-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bl-flatred.png --export-id=debug-bl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-br-flatred.png --export-id=debug-br-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bot-flatred.png --export-id=debug-bot-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-top-flatred.png --export-id=qa-top-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tl-flatred.png --export-id=qa-tl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tr-flatred.png --export-id=qa-tr-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bl-flatred.png --export-id=qa-bl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-br-flatred.png --export-id=qa-br-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bot-flatred.png --export-id=qa-bot-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-top-flatred.png --export-id=uat-top-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tl-flatred.png --export-id=uat-tl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tr-flatred.png --export-id=uat-tr-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bl-flatred.png --export-id=uat-bl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-br-flatred.png --export-id=uat-br-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bot-flatred.png --export-id=uat-bot-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-top-flatred.png --export-id=stage-top-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tl-flatred.png --export-id=stage-tl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tr-flatred.png --export-id=stage-tr-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bl-flatred.png --export-id=stage-bl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-br-flatred.png --export-id=stage-br-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bot-flatred.png --export-id=stage-bot-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-top-flatred.png --export-id=preview-top-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tl-flatred.png --export-id=preview-tl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tr-flatred.png --export-id=preview-tr-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bl-flatred.png --export-id=preview-bl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-br-flatred.png --export-id=preview-br-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bot-flatred.png --export-id=preview-bot-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-top-flatred.png --export-id=alpha-top-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tl-flatred.png --export-id=alpha-tl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tr-flatred.png --export-id=alpha-tr-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bl-flatred.png --export-id=alpha-bl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-br-flatred.png --export-id=alpha-br-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bot-flatred.png --export-id=alpha-bot-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-top-flatred.png --export-id=beta-top-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tl-flatred.png --export-id=beta-tl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tr-flatred.png --export-id=beta-tr-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bl-flatred.png --export-id=beta-bl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-br-flatred.png --export-id=beta-br-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bot-flatred.png --export-id=beta-bot-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-top-flatred.png --export-id=free-top-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tl-flatred.png --export-id=free-tl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tr-flatred.png --export-id=free-tr-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bl-flatred.png --export-id=free-bl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-br-flatred.png --export-id=free-br-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bot-flatred.png --export-id=free-bot-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-top-flatred.png --export-id=pro-top-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tl-flatred.png --export-id=pro-tl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tr-flatred.png --export-id=pro-tr-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bl-flatred.png --export-id=pro-bl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-br-flatred.png --export-id=pro-br-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bot-flatred.png --export-id=pro-bot-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-top-flatred.png --export-id=lite-top-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tl-flatred.png --export-id=lite-tl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tr-flatred.png --export-id=lite-tr-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bl-flatred.png --export-id=lite-bl-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-br-flatred.png --export-id=lite-br-flatred flatred.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bot-flatred.png --export-id=lite-bot-flatred flatred.svg
