cls
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-top-flatorange.png --export-id=dev-top-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tl-flatorange.png --export-id=dev-tl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tr-flatorange.png --export-id=dev-tr-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bl-flatorange.png --export-id=dev-bl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-br-flatorange.png --export-id=dev-br-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bot-flatorange.png --export-id=dev-bot-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-top-flatorange.png --export-id=debug-top-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tl-flatorange.png --export-id=debug-tl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tr-flatorange.png --export-id=debug-tr-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bl-flatorange.png --export-id=debug-bl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-br-flatorange.png --export-id=debug-br-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bot-flatorange.png --export-id=debug-bot-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-top-flatorange.png --export-id=qa-top-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tl-flatorange.png --export-id=qa-tl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tr-flatorange.png --export-id=qa-tr-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bl-flatorange.png --export-id=qa-bl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-br-flatorange.png --export-id=qa-br-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bot-flatorange.png --export-id=qa-bot-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-top-flatorange.png --export-id=uat-top-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tl-flatorange.png --export-id=uat-tl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tr-flatorange.png --export-id=uat-tr-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bl-flatorange.png --export-id=uat-bl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-br-flatorange.png --export-id=uat-br-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bot-flatorange.png --export-id=uat-bot-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-top-flatorange.png --export-id=stage-top-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tl-flatorange.png --export-id=stage-tl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tr-flatorange.png --export-id=stage-tr-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bl-flatorange.png --export-id=stage-bl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-br-flatorange.png --export-id=stage-br-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bot-flatorange.png --export-id=stage-bot-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-top-flatorange.png --export-id=preview-top-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tl-flatorange.png --export-id=preview-tl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tr-flatorange.png --export-id=preview-tr-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bl-flatorange.png --export-id=preview-bl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-br-flatorange.png --export-id=preview-br-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bot-flatorange.png --export-id=preview-bot-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-top-flatorange.png --export-id=alpha-top-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tl-flatorange.png --export-id=alpha-tl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tr-flatorange.png --export-id=alpha-tr-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bl-flatorange.png --export-id=alpha-bl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-br-flatorange.png --export-id=alpha-br-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bot-flatorange.png --export-id=alpha-bot-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-top-flatorange.png --export-id=beta-top-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tl-flatorange.png --export-id=beta-tl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tr-flatorange.png --export-id=beta-tr-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bl-flatorange.png --export-id=beta-bl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-br-flatorange.png --export-id=beta-br-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bot-flatorange.png --export-id=beta-bot-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-top-flatorange.png --export-id=free-top-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tl-flatorange.png --export-id=free-tl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tr-flatorange.png --export-id=free-tr-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bl-flatorange.png --export-id=free-bl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-br-flatorange.png --export-id=free-br-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bot-flatorange.png --export-id=free-bot-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-top-flatorange.png --export-id=pro-top-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tl-flatorange.png --export-id=pro-tl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tr-flatorange.png --export-id=pro-tr-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bl-flatorange.png --export-id=pro-bl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-br-flatorange.png --export-id=pro-br-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bot-flatorange.png --export-id=pro-bot-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-top-flatorange.png --export-id=lite-top-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tl-flatorange.png --export-id=lite-tl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tr-flatorange.png --export-id=lite-tr-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bl-flatorange.png --export-id=lite-bl-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-br-flatorange.png --export-id=lite-br-flatorange flatorange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bot-flatorange.png --export-id=lite-bot-flatorange flatorange.svg
