cls
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-top-flatblack.png --export-id=dev-top-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tl-flatblack.png --export-id=dev-tl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tr-flatblack.png --export-id=dev-tr-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bl-flatblack.png --export-id=dev-bl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-br-flatblack.png --export-id=dev-br-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bot-flatblack.png --export-id=dev-bot-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-top-flatblack.png --export-id=debug-top-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tl-flatblack.png --export-id=debug-tl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tr-flatblack.png --export-id=debug-tr-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bl-flatblack.png --export-id=debug-bl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-br-flatblack.png --export-id=debug-br-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bot-flatblack.png --export-id=debug-bot-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-top-flatblack.png --export-id=qa-top-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tl-flatblack.png --export-id=qa-tl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tr-flatblack.png --export-id=qa-tr-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bl-flatblack.png --export-id=qa-bl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-br-flatblack.png --export-id=qa-br-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bot-flatblack.png --export-id=qa-bot-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-top-flatblack.png --export-id=uat-top-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tl-flatblack.png --export-id=uat-tl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tr-flatblack.png --export-id=uat-tr-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bl-flatblack.png --export-id=uat-bl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-br-flatblack.png --export-id=uat-br-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bot-flatblack.png --export-id=uat-bot-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-top-flatblack.png --export-id=stage-top-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tl-flatblack.png --export-id=stage-tl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tr-flatblack.png --export-id=stage-tr-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bl-flatblack.png --export-id=stage-bl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-br-flatblack.png --export-id=stage-br-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bot-flatblack.png --export-id=stage-bot-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-top-flatblack.png --export-id=preview-top-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tl-flatblack.png --export-id=preview-tl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tr-flatblack.png --export-id=preview-tr-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bl-flatblack.png --export-id=preview-bl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-br-flatblack.png --export-id=preview-br-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bot-flatblack.png --export-id=preview-bot-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-top-flatblack.png --export-id=alpha-top-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tl-flatblack.png --export-id=alpha-tl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tr-flatblack.png --export-id=alpha-tr-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bl-flatblack.png --export-id=alpha-bl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-br-flatblack.png --export-id=alpha-br-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bot-flatblack.png --export-id=alpha-bot-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-top-flatblack.png --export-id=beta-top-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tl-flatblack.png --export-id=beta-tl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tr-flatblack.png --export-id=beta-tr-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bl-flatblack.png --export-id=beta-bl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-br-flatblack.png --export-id=beta-br-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bot-flatblack.png --export-id=beta-bot-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-top-flatblack.png --export-id=free-top-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tl-flatblack.png --export-id=free-tl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tr-flatblack.png --export-id=free-tr-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bl-flatblack.png --export-id=free-bl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-br-flatblack.png --export-id=free-br-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bot-flatblack.png --export-id=free-bot-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-top-flatblack.png --export-id=pro-top-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tl-flatblack.png --export-id=pro-tl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tr-flatblack.png --export-id=pro-tr-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bl-flatblack.png --export-id=pro-bl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-br-flatblack.png --export-id=pro-br-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bot-flatblack.png --export-id=pro-bot-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-top-flatblack.png --export-id=lite-top-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tl-flatblack.png --export-id=lite-tl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tr-flatblack.png --export-id=lite-tr-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bl-flatblack.png --export-id=lite-bl-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-br-flatblack.png --export-id=lite-br-flatblack flatblack.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bot-flatblack.png --export-id=lite-bot-flatblack flatblack.svg

