cls
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-top-red.png --export-id=dev-top-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tl-red.png --export-id=dev-tl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tr-red.png --export-id=dev-tr-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bl-red.png --export-id=dev-bl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-br-red.png --export-id=dev-br-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bot-red.png --export-id=dev-bot-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-top-red.png --export-id=debug-top-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tl-red.png --export-id=debug-tl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tr-red.png --export-id=debug-tr-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bl-red.png --export-id=debug-bl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-br-red.png --export-id=debug-br-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bot-red.png --export-id=debug-bot-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-top-red.png --export-id=qa-top-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tl-red.png --export-id=qa-tl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tr-red.png --export-id=qa-tr-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bl-red.png --export-id=qa-bl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-br-red.png --export-id=qa-br-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bot-red.png --export-id=qa-bot-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-top-red.png --export-id=uat-top-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tl-red.png --export-id=uat-tl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tr-red.png --export-id=uat-tr-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bl-red.png --export-id=uat-bl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-br-red.png --export-id=uat-br-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bot-red.png --export-id=uat-bot-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-top-red.png --export-id=stage-top-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tl-red.png --export-id=stage-tl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tr-red.png --export-id=stage-tr-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bl-red.png --export-id=stage-bl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-br-red.png --export-id=stage-br-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bot-red.png --export-id=stage-bot-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-top-red.png --export-id=preview-top-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tl-red.png --export-id=preview-tl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tr-red.png --export-id=preview-tr-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bl-red.png --export-id=preview-bl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-br-red.png --export-id=preview-br-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bot-red.png --export-id=preview-bot-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-top-red.png --export-id=alpha-top-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tl-red.png --export-id=alpha-tl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tr-red.png --export-id=alpha-tr-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bl-red.png --export-id=alpha-bl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-br-red.png --export-id=alpha-br-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bot-red.png --export-id=alpha-bot-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-top-red.png --export-id=beta-top-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tl-red.png --export-id=beta-tl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tr-red.png --export-id=beta-tr-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bl-red.png --export-id=beta-bl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-br-red.png --export-id=beta-br-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bot-red.png --export-id=beta-bot-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-top-red.png --export-id=free-top-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tl-red.png --export-id=free-tl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tr-red.png --export-id=free-tr-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bl-red.png --export-id=free-bl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-br-red.png --export-id=free-br-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bot-red.png --export-id=free-bot-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-top-red.png --export-id=pro-top-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tl-red.png --export-id=pro-tl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tr-red.png --export-id=pro-tr-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bl-red.png --export-id=pro-bl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-br-red.png --export-id=pro-br-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bot-red.png --export-id=pro-bot-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-top-red.png --export-id=lite-top-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tl-red.png --export-id=lite-tl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tr-red.png --export-id=lite-tr-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bl-red.png --export-id=lite-bl-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-br-red.png --export-id=lite-br-red red.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bot-red.png --export-id=lite-bot-red red.svg
