cls
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-top-orange.png --export-id=dev-top-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tl-orange.png --export-id=dev-tl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tr-orange.png --export-id=dev-tr-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bl-orange.png --export-id=dev-bl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-br-orange.png --export-id=dev-br-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bot-orange.png --export-id=dev-bot-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-top-orange.png --export-id=debug-top-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tl-orange.png --export-id=debug-tl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tr-orange.png --export-id=debug-tr-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bl-orange.png --export-id=debug-bl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-br-orange.png --export-id=debug-br-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bot-orange.png --export-id=debug-bot-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-top-orange.png --export-id=qa-top-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tl-orange.png --export-id=qa-tl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tr-orange.png --export-id=qa-tr-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bl-orange.png --export-id=qa-bl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-br-orange.png --export-id=qa-br-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bot-orange.png --export-id=qa-bot-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-top-orange.png --export-id=uat-top-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tl-orange.png --export-id=uat-tl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tr-orange.png --export-id=uat-tr-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bl-orange.png --export-id=uat-bl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-br-orange.png --export-id=uat-br-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bot-orange.png --export-id=uat-bot-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-top-orange.png --export-id=stage-top-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tl-orange.png --export-id=stage-tl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tr-orange.png --export-id=stage-tr-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bl-orange.png --export-id=stage-bl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-br-orange.png --export-id=stage-br-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bot-orange.png --export-id=stage-bot-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-top-orange.png --export-id=preview-top-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tl-orange.png --export-id=preview-tl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tr-orange.png --export-id=preview-tr-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bl-orange.png --export-id=preview-bl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-br-orange.png --export-id=preview-br-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bot-orange.png --export-id=preview-bot-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-top-orange.png --export-id=alpha-top-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tl-orange.png --export-id=alpha-tl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tr-orange.png --export-id=alpha-tr-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bl-orange.png --export-id=alpha-bl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-br-orange.png --export-id=alpha-br-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bot-orange.png --export-id=alpha-bot-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-top-orange.png --export-id=beta-top-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tl-orange.png --export-id=beta-tl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tr-orange.png --export-id=beta-tr-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bl-orange.png --export-id=beta-bl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-br-orange.png --export-id=beta-br-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bot-orange.png --export-id=beta-bot-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-top-orange.png --export-id=free-top-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tl-orange.png --export-id=free-tl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tr-orange.png --export-id=free-tr-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bl-orange.png --export-id=free-bl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-br-orange.png --export-id=free-br-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bot-orange.png --export-id=free-bot-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-top-orange.png --export-id=pro-top-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tl-orange.png --export-id=pro-tl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tr-orange.png --export-id=pro-tr-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bl-orange.png --export-id=pro-bl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-br-orange.png --export-id=pro-br-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bot-orange.png --export-id=pro-bot-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-top-orange.png --export-id=lite-top-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tl-orange.png --export-id=lite-tl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tr-orange.png --export-id=lite-tr-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bl-orange.png --export-id=lite-bl-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-br-orange.png --export-id=lite-br-orange orange.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bot-orange.png --export-id=lite-bot-orange orange.svg
