cls
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-top-flatwhite.png --export-id=dev-top-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tl-flatwhite.png --export-id=dev-tl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tr-flatwhite.png --export-id=dev-tr-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bl-flatwhite.png --export-id=dev-bl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-br-flatwhite.png --export-id=dev-br-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bot-flatwhite.png --export-id=dev-bot-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-top-flatwhite.png --export-id=debug-top-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tl-flatwhite.png --export-id=debug-tl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tr-flatwhite.png --export-id=debug-tr-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bl-flatwhite.png --export-id=debug-bl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-br-flatwhite.png --export-id=debug-br-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bot-flatwhite.png --export-id=debug-bot-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-top-flatwhite.png --export-id=qa-top-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tl-flatwhite.png --export-id=qa-tl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tr-flatwhite.png --export-id=qa-tr-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bl-flatwhite.png --export-id=qa-bl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-br-flatwhite.png --export-id=qa-br-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bot-flatwhite.png --export-id=qa-bot-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-top-flatwhite.png --export-id=uat-top-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tl-flatwhite.png --export-id=uat-tl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tr-flatwhite.png --export-id=uat-tr-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bl-flatwhite.png --export-id=uat-bl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-br-flatwhite.png --export-id=uat-br-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bot-flatwhite.png --export-id=uat-bot-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-top-flatwhite.png --export-id=stage-top-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tl-flatwhite.png --export-id=stage-tl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tr-flatwhite.png --export-id=stage-tr-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bl-flatwhite.png --export-id=stage-bl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-br-flatwhite.png --export-id=stage-br-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bot-flatwhite.png --export-id=stage-bot-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-top-flatwhite.png --export-id=preview-top-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tl-flatwhite.png --export-id=preview-tl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tr-flatwhite.png --export-id=preview-tr-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bl-flatwhite.png --export-id=preview-bl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-br-flatwhite.png --export-id=preview-br-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bot-flatwhite.png --export-id=preview-bot-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-top-flatwhite.png --export-id=alpha-top-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tl-flatwhite.png --export-id=alpha-tl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tr-flatwhite.png --export-id=alpha-tr-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bl-flatwhite.png --export-id=alpha-bl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-br-flatwhite.png --export-id=alpha-br-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bot-flatwhite.png --export-id=alpha-bot-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-top-flatwhite.png --export-id=beta-top-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tl-flatwhite.png --export-id=beta-tl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tr-flatwhite.png --export-id=beta-tr-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bl-flatwhite.png --export-id=beta-bl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-br-flatwhite.png --export-id=beta-br-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bot-flatwhite.png --export-id=beta-bot-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-top-flatwhite.png --export-id=free-top-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tl-flatwhite.png --export-id=free-tl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tr-flatwhite.png --export-id=free-tr-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bl-flatwhite.png --export-id=free-bl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-br-flatwhite.png --export-id=free-br-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bot-flatwhite.png --export-id=free-bot-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-top-flatwhite.png --export-id=pro-top-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tl-flatwhite.png --export-id=pro-tl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tr-flatwhite.png --export-id=pro-tr-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bl-flatwhite.png --export-id=pro-bl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-br-flatwhite.png --export-id=pro-br-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bot-flatwhite.png --export-id=pro-bot-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-top-flatwhite.png --export-id=lite-top-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tl-flatwhite.png --export-id=lite-tl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tr-flatwhite.png --export-id=lite-tr-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bl-flatwhite.png --export-id=lite-bl-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-br-flatwhite.png --export-id=lite-br-flatwhite flatwhite.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bot-flatwhite.png --export-id=lite-bot-flatwhite flatwhite.svg
