cls
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-top-flatblue.png --export-id=dev-top-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tl-flatblue.png --export-id=dev-tl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tr-flatblue.png --export-id=dev-tr-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bl-flatblue.png --export-id=dev-bl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-br-flatblue.png --export-id=dev-br-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bot-flatblue.png --export-id=dev-bot-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-top-flatblue.png --export-id=debug-top-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tl-flatblue.png --export-id=debug-tl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tr-flatblue.png --export-id=debug-tr-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bl-flatblue.png --export-id=debug-bl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-br-flatblue.png --export-id=debug-br-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bot-flatblue.png --export-id=debug-bot-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-top-flatblue.png --export-id=qa-top-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tl-flatblue.png --export-id=qa-tl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tr-flatblue.png --export-id=qa-tr-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bl-flatblue.png --export-id=qa-bl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-br-flatblue.png --export-id=qa-br-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bot-flatblue.png --export-id=qa-bot-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-top-flatblue.png --export-id=uat-top-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tl-flatblue.png --export-id=uat-tl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tr-flatblue.png --export-id=uat-tr-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bl-flatblue.png --export-id=uat-bl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-br-flatblue.png --export-id=uat-br-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bot-flatblue.png --export-id=uat-bot-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-top-flatblue.png --export-id=stage-top-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tl-flatblue.png --export-id=stage-tl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tr-flatblue.png --export-id=stage-tr-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bl-flatblue.png --export-id=stage-bl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-br-flatblue.png --export-id=stage-br-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bot-flatblue.png --export-id=stage-bot-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-top-flatblue.png --export-id=preview-top-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tl-flatblue.png --export-id=preview-tl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tr-flatblue.png --export-id=preview-tr-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bl-flatblue.png --export-id=preview-bl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-br-flatblue.png --export-id=preview-br-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bot-flatblue.png --export-id=preview-bot-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-top-flatblue.png --export-id=alpha-top-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tl-flatblue.png --export-id=alpha-tl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tr-flatblue.png --export-id=alpha-tr-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bl-flatblue.png --export-id=alpha-bl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-br-flatblue.png --export-id=alpha-br-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bot-flatblue.png --export-id=alpha-bot-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-top-flatblue.png --export-id=beta-top-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tl-flatblue.png --export-id=beta-tl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tr-flatblue.png --export-id=beta-tr-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bl-flatblue.png --export-id=beta-bl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-br-flatblue.png --export-id=beta-br-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bot-flatblue.png --export-id=beta-bot-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-top-flatblue.png --export-id=free-top-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tl-flatblue.png --export-id=free-tl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tr-flatblue.png --export-id=free-tr-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bl-flatblue.png --export-id=free-bl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-br-flatblue.png --export-id=free-br-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bot-flatblue.png --export-id=free-bot-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-top-flatblue.png --export-id=pro-top-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tl-flatblue.png --export-id=pro-tl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tr-flatblue.png --export-id=pro-tr-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bl-flatblue.png --export-id=pro-bl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-br-flatblue.png --export-id=pro-br-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bot-flatblue.png --export-id=pro-bot-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-top-flatblue.png --export-id=lite-top-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tl-flatblue.png --export-id=lite-tl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tr-flatblue.png --export-id=lite-tr-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bl-flatblue.png --export-id=lite-bl-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-br-flatblue.png --export-id=lite-br-flatblue flatblue.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bot-flatblue.png --export-id=lite-bot-flatblue flatblue.svg

