cls
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-top-black.png --export-id=dev-top-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tl-black.png --export-id=dev-tl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tr-black.png --export-id=dev-tr-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bl-black.png --export-id=dev-bl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-br-black.png --export-id=dev-br-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bot-black.png --export-id=dev-bot-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-top-black.png --export-id=debug-top-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tl-black.png --export-id=debug-tl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tr-black.png --export-id=debug-tr-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bl-black.png --export-id=debug-bl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-br-black.png --export-id=debug-br-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bot-black.png --export-id=debug-bot-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-top-black.png --export-id=qa-top-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tl-black.png --export-id=qa-tl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tr-black.png --export-id=qa-tr-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bl-black.png --export-id=qa-bl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-br-black.png --export-id=qa-br-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bot-black.png --export-id=qa-bot-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-top-black.png --export-id=uat-top-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tl-black.png --export-id=uat-tl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tr-black.png --export-id=uat-tr-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bl-black.png --export-id=uat-bl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-br-black.png --export-id=uat-br-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bot-black.png --export-id=uat-bot-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-top-black.png --export-id=stage-top-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tl-black.png --export-id=stage-tl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tr-black.png --export-id=stage-tr-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bl-black.png --export-id=stage-bl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-br-black.png --export-id=stage-br-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bot-black.png --export-id=stage-bot-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-top-black.png --export-id=preview-top-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tl-black.png --export-id=preview-tl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tr-black.png --export-id=preview-tr-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bl-black.png --export-id=preview-bl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-br-black.png --export-id=preview-br-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bot-black.png --export-id=preview-bot-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-top-black.png --export-id=alpha-top-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tl-black.png --export-id=alpha-tl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tr-black.png --export-id=alpha-tr-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bl-black.png --export-id=alpha-bl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-br-black.png --export-id=alpha-br-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bot-black.png --export-id=alpha-bot-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-top-black.png --export-id=beta-top-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tl-black.png --export-id=beta-tl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tr-black.png --export-id=beta-tr-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bl-black.png --export-id=beta-bl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-br-black.png --export-id=beta-br-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bot-black.png --export-id=beta-bot-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-top-black.png --export-id=free-top-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tl-black.png --export-id=free-tl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tr-black.png --export-id=free-tr-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bl-black.png --export-id=free-bl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-br-black.png --export-id=free-br-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bot-black.png --export-id=free-bot-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-top-black.png --export-id=pro-top-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tl-black.png --export-id=pro-tl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tr-black.png --export-id=pro-tr-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bl-black.png --export-id=pro-bl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-br-black.png --export-id=pro-br-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bot-black.png --export-id=pro-bot-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-top-black.png --export-id=lite-top-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tl-black.png --export-id=lite-tl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tr-black.png --export-id=lite-tr-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bl-black.png --export-id=lite-bl-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-br-black.png --export-id=lite-br-black black.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bot-black.png --export-id=lite-bot-black black.svg
