cls
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-top-purple.png --export-id=dev-top-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tl-purple.png --export-id=dev-tl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-tr-purple.png --export-id=dev-tr-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bl-purple.png --export-id=dev-bl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-br-purple.png --export-id=dev-br-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\dev-bot-purple.png --export-id=dev-bot-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-top-purple.png --export-id=debug-top-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tl-purple.png --export-id=debug-tl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-tr-purple.png --export-id=debug-tr-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bl-purple.png --export-id=debug-bl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-br-purple.png --export-id=debug-br-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\debug-bot-purple.png --export-id=debug-bot-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-top-purple.png --export-id=qa-top-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tl-purple.png --export-id=qa-tl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-tr-purple.png --export-id=qa-tr-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bl-purple.png --export-id=qa-bl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-br-purple.png --export-id=qa-br-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\qa-bot-purple.png --export-id=qa-bot-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-top-purple.png --export-id=uat-top-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tl-purple.png --export-id=uat-tl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-tr-purple.png --export-id=uat-tr-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bl-purple.png --export-id=uat-bl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-br-purple.png --export-id=uat-br-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\uat-bot-purple.png --export-id=uat-bot-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-top-purple.png --export-id=stage-top-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tl-purple.png --export-id=stage-tl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-tr-purple.png --export-id=stage-tr-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bl-purple.png --export-id=stage-bl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-br-purple.png --export-id=stage-br-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\stage-bot-purple.png --export-id=stage-bot-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-top-purple.png --export-id=preview-top-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tl-purple.png --export-id=preview-tl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-tr-purple.png --export-id=preview-tr-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bl-purple.png --export-id=preview-bl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-br-purple.png --export-id=preview-br-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\preview-bot-purple.png --export-id=preview-bot-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-top-purple.png --export-id=alpha-top-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tl-purple.png --export-id=alpha-tl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-tr-purple.png --export-id=alpha-tr-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bl-purple.png --export-id=alpha-bl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-br-purple.png --export-id=alpha-br-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\alpha-bot-purple.png --export-id=alpha-bot-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-top-purple.png --export-id=beta-top-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tl-purple.png --export-id=beta-tl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-tr-purple.png --export-id=beta-tr-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bl-purple.png --export-id=beta-bl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-br-purple.png --export-id=beta-br-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\beta-bot-purple.png --export-id=beta-bot-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-top-purple.png --export-id=free-top-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tl-purple.png --export-id=free-tl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-tr-purple.png --export-id=free-tr-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bl-purple.png --export-id=free-bl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-br-purple.png --export-id=free-br-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\free-bot-purple.png --export-id=free-bot-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-top-purple.png --export-id=pro-top-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tl-purple.png --export-id=pro-tl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-tr-purple.png --export-id=pro-tr-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bl-purple.png --export-id=pro-bl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-br-purple.png --export-id=pro-br-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\pro-bot-purple.png --export-id=pro-bot-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-top-purple.png --export-id=lite-top-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tl-purple.png --export-id=lite-tl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-tr-purple.png --export-id=lite-tr-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bl-purple.png --export-id=lite-bl-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-br-purple.png --export-id=lite-br-purple purple.svg
"C:\Program Files\Inkscape\inkscape.exe" --export-png=..\lite-bot-purple.png --export-id=lite-bot-purple purple.svg
