//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Mobile.BuildTools. For more information please visit
//     https://mobilebuildtools.com or to file an issue please see
//     https://github.com/dansiegel/Mobile.BuildTools
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
//
//     When I wrote this, only God and I understood what I was doing
//     Now, God only knows.
//
//     NOTE: This file should be excluded from source control.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using GeneratedCodeAttribute = System.CodeDom.Compiler.GeneratedCodeAttribute;

namespace TestProject.Helpers
{
    internal static partial class AppSettings
    {
        [GeneratedCodeAttribute("Mobile.BuildTools.AppSettings.Generators.AppSettingsGenerator", "{0}")]
        public const string AProperty =
            "Hello World";
    }
}
