<Project>
  <PropertyGroup>
    <_MobileBuildToolsTaskHost Condition="'$(MSBuildRuntimeType)' == 'Core'">net10.0</_MobileBuildToolsTaskHost>
    <_MobileBuildToolsTaskHost Condition="'$(_MobileBuildToolsTaskHost)' == ''">net472</_MobileBuildToolsTaskHost>
    <_MobileBuildToolsAppManifestTasksDll>$(MSBuildThisFileDirectory)tasks/$(_MobileBuildToolsTaskHost)/Mobile.BuildTools.AppManifests.dll</_MobileBuildToolsAppManifestTasksDll>
    <_MBTManifestPlatform>$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)'))</_MBTManifestPlatform>
  </PropertyGroup>
  <UsingTask TaskName="Mobile.BuildTools.Tasks.AutomaticBuildVersioningTask" AssemblyFile="$(_MobileBuildToolsAppManifestTasksDll)" />
  <UsingTask TaskName="Mobile.BuildTools.Tasks.TemplateManifestTask" AssemblyFile="$(_MobileBuildToolsAppManifestTasksDll)" />
  <UsingTask TaskName="Mobile.BuildTools.Tasks.TransformManifestItemsTask" AssemblyFile="$(_MobileBuildToolsAppManifestTasksDll)" />
  <Import Project="AndroidManifest.targets" Condition="'$(_MBTManifestPlatform)' == 'android' Or '$(TargetFrameworkIdentifier)' == 'MonoAndroid'" />
  <Import Project="AppleManifests.targets" Condition="'$(_MBTManifestPlatform)' == 'ios' Or '$(_MBTManifestPlatform)' == 'maccatalyst' Or '$(_MBTManifestPlatform)' == 'macos' Or '$(_MBTManifestPlatform)' == 'tvos' Or '$(TargetFrameworkIdentifier)' == 'Xamarin.iOS' Or '$(TargetFrameworkIdentifier)' == 'Xamarin.Mac'" />
  <Import Project="WindowsManifest.targets" />
  <Import Project="WebAssemblyManifest.targets" Condition="'$(_MBTManifestPlatform)' == 'browser' Or '$(_MBTManifestPlatform)' == 'browserwasm' Or '$(RuntimeIdentifier)' == 'browser-wasm'" />
</Project>
