name: CI

on:
  push:
    branches: [master]
    paths:
    - 'Directory.*'
    - 'src/**'
    - 'E2E/**'
    - 'tests/**'

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    uses: avantipoint/workflow-templates/.github/workflows/msbuild-build.yml@master
    with:
      name: Build Mobile.BuildTools
      solution-path: Mobile.BuildTools.sln
      submodules: true
      dotnet-version: '10.0.x'
      jdk-version: '21'
      install-workload: 'maui macos'
      vs-version: '18.0'
      code-sign: true
      codeSignEndpoint: https://eus.codesigning.azure.net/
      codeSignAccountName: avantipoint-signing
      codeSignCertificateProfile: AvantiPoint
    secrets:
      codeSignClientId: ${{ secrets.CodeSignClientId }}
      codeSignTenantId: ${{ secrets.CodeSignTenantId }}

  deploy-internal:
    uses: avantipoint/workflow-templates/.github/workflows/deploy-nuget.yml@master
    needs: build
    if: ${{ github.event_name == 'push' }}
    with:
      name: Deploy Internal
    secrets:
      feedUrl: ${{ secrets.IN_HOUSE_NUGET_FEED }}
      apiKey: ${{ secrets.IN_HOUSE_API_KEY }}

  deploy-sponsors:
    uses: avantipoint/workflow-templates/.github/workflows/deploy-nuget.yml@master
    needs: build
    if: ${{ github.event_name == 'push' }}
    with:
      name: Deploy Sponsor Connect
    secrets:
      feedUrl: ${{ secrets.SPONSOR_CONNECT_NUGET_FEED }}
      apiKey: ${{ secrets.SPONSOR_CONNECT_TOKEN }}

