name: CI

on:
  push:
    branches: [master]
    paths:
    - 'Directory.*'
    - 'src/**'
    - 'E2E/**'
    - 'tests/**'

jobs:
  build:
    uses: avantipoint/workflow-templates/.github/workflows/msbuild-build.yml@master
    with:
      name: Build Mobile.BuildTools
      solution-path: Mobile.BuildTools.sln
      submodules: true
      install-workload: 'maui macos maui-tizen'
      uno-check: true
      vs-version: 17.8
      code-sign: true
    secrets:
      codeSignKeyVault: ${{ secrets.CodeSignKeyVault }}
      codeSignClientId: ${{ secrets.CodeSignClientId }}
      codeSignTenantId: ${{ secrets.CodeSignTenantId }}
      codeSignClientSecret: ${{ secrets.CodeSignClientSecret }}
      codeSignCertificate: ${{ secrets.CodeSignCertificate }}

  deploy-internal:
    uses: avantipoint/workflow-templates/.github/workflows/deploy-nuget.yml@master
    needs: build
    if: ${{ github.event_name == 'push' }}
    with:
      name: Deploy Internal
    secrets:
      feedUrl: ${{ secrets.IN_HOUSE_NUGET_FEED }}
      apiKey: ${{ secrets.IN_HOUSE_API_KEY }}

  deploy-sponsors:
    uses: avantipoint/workflow-templates/.github/workflows/deploy-nuget.yml@master
    needs: build
    if: ${{ github.event_name == 'push' }}
    with:
      name: Deploy Sponsor Connect
    secrets:
      feedUrl: ${{ secrets.SPONSOR_CONNECT_NUGET_FEED }}
      apiKey: ${{ secrets.SPONSOR_CONNECT_TOKEN }}
