name: Start NuGet Release

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    uses: avantipoint/workflow-templates/.github/workflows/msbuild-build.yml@master
    with:
      name: Build Mobile.BuildTools
      solution-path: Mobile.BuildTools.sln
      submodules: true
      dotnet-version: '10.0.x'
      jdk-version: '21'
      install-workload: 'maui macos'
      uno-check: true
      vs-version: '18.0'
      code-sign: true
      codeSignEndpoint: https://eus.codesigning.azure.net/
      codeSignAccountName: avantipoint-signing
      codeSignCertificateProfile: AvantiPoint
    secrets:
      codeSignClientId: ${{ secrets.CodeSignClientId }}
      codeSignTenantId: ${{ secrets.CodeSignTenantId }}

  release:
    uses: avantipoint/workflow-templates/.github/workflows/generate-release.yml@master
    needs: [build]
    permissions:
      contents: write
    with:
      package-name: Mobile.BuildTools
      artifacts: "Artifacts/*.nupkg,Artifacts/*.snupkg,Artifacts/*.zip"

